Repository OpenEnergyPlatform/oeplatform, pull requests merged in 2020-05, with the labels that each got.

#599 Feauture/ffs implement feedback
  modelview/migrations/0051_auto_20200407_1842.py
  modelview/migrations/0052_auto_20200408_1308.py
  modelview/migrations/0053_auto_20200408_1442.py
  modelview/migrations/0054_auto_20200408_1539.py
  modelview/models.py
  modelview/templates/modelview/editframework.html
  modelview/templates/modelview/framework.html
  versions/changelogs/current.md
Labels: Factsheets, Feedback

#606 Feature/oefamily#596
  base/static/img/OpenEnergyFamily_modules_trans.png
  base/static/logos/DLR-VE.png
  base/static/logos/HZG.png
  base/static/logos/SzenarienDB_Header.png
  base/static/logos/open_FRED_Header.png
  base/static/logos/open_eGo_Header.png
  base/templates/base/about.html
Labels: Content, design/layout, enhancement, help wanted

#605 Feature/oeo steering committe subpage
  ontology/templates/ontology/about.html
  ontology/templates/ontology/oeo-steering-committee.html
  ontology/urls.py
Labels: Content, design/layout
