Repository OpenEnergyPlatform/oeplatform, pull requests merged in 2022-06, with the labels that each got.

#983 Update Factsheets Overview #801
  modelview/templates/modelview/overview.html
  versions/changelogs/current.md
Labels: help wanted, design/layout, Content

#987 Remove link to Study Factsheets (alpha) in navigation bar #981
  base/templates/base/base-wide.html
  base/templates/base/base.html
  versions/changelogs/current.md
Labels: Factsheets, Content

#978 Improve dataedit filter sidebar (improve tag search and tooltips)
  dataedit/templates/dataedit/filter.html
  versions/changelogs/current.md
Labels: design/layout, Content, Tags, data view / modification

#1007 Update filter description
  dataedit/templates/dataedit/filter.html
  versions/changelogs/current.md
Labels: Content
